agenda/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

"""
URL configuration for agenda project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('fornecedores.urls')),
    path('', include('clientes.urls')),
    path('', include('produtos.urls')),
    path('', include('funcionarios.urls')),
    path('', include('servicos.urls')),
    path('', include('agendamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agendamentos/urls.py
from django.urls import path
from .views import AgendamentosView, AgendamentoAddView, AgendamentoUpdateView, AgendamentoDeleteView, \
    AgendamentoToInLineEditView, AgendamentoExibir

urlpatterns = [
    path('agendamentos/', AgendamentosView.as_view(), name='agendamentos'),
    path('agendamento/adicionar/', AgendamentoAddView.as_view(), name='agendamento_adicionar'),
    path('<int:pk>/agendamento/editar/', AgendamentoUpdateView.as_view(), name='agendamento_editar'),
    path('<int:pk>/agendamento/apagar/', AgendamentoDeleteView.as_view(), name='agendamento_apagar'),
    path('<int:pk>/agendamento/inline', AgendamentoToInLineEditView.as_view(), name='agendamento_inline'),
    path('<int:pk>/agendamento/exibir/', AgendamentoExibir.as_view(), name='agendamento_exibir')
]

home/urls.py
from .views import IndexView
from django.urls import path

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

agendamentos/models.py
from django.db import models
from django.db.models.functions import Upper

from servicos.models import Servico


class Agendamento(models.Model):
    horario = models.DateTimeField('Horário', help_text='Data e hora do atendimento')
    cliente = models.ForeignKey('clientes.Cliente', verbose_name='Cliente',
                                    help_text='Nome do Cliente', on_delete=models.PROTECT)
    funcionario = models.ForeignKey('funcionarios.Funcionario', verbose_name='Funcionario',
                                    help_text='Nome do Funcionário', on_delete=models.PROTECT)
    servico = models.ManyToManyField('servicos.Servico', verbose_name='Serviço', through='agendamentos.OrdemServicos')

    valor = models.DecimalField( verbose_name='Valor total',decimal_places=2, max_digits=6, default=0.00)
    status = models.CharField( verbose_name='Status', max_length=1, help_text='Status do agendamento', default='A')
    @property
    def servicos(self):
        return OrdemServicos.objects.filter(agendamento=self)

    class Meta:
        verbose_name = 'Agendamento'
        verbose_name_plural = 'Agendamentos'
        ordering = ['-horario']

    def __str__(self):
        return f'Cliente: {self.cliente}'

class OrdemServicos(models.Model):
    SITUACAO_OPCOES = (
        ('A', 'Agendado'),
        ('R', 'Realizado'),
        ('C', 'Cancelado'),
    )

    agendamento = models.ForeignKey('agendamentos.Agendamento', verbose_name='Agendamento', on_delete=models.CASCADE, related_name='agendamento')

    servico = models.ForeignKey('servicos.Servico', verbose_name='Serviço', on_delete=models.PROTECT, related_name='ordem_servico')

    funcionario = models.ForeignKey('funcionarios.Funcionario', verbose_name='Funcionário', on_delete=models.PROTECT, related_name='funcionario')

    situacao = models.CharField('Situação', max_length=1, choices=SITUACAO_OPCOES, default='A')
    observacoes = models.TextField('Observações', max_length=300, blank=True, null=True)
    preco = models.DecimalField('Preço', max_digits=6, decimal_places=2, help_text='Preço do serviço', default=0.00)

    class Meta:
        verbose_name = 'Serviço realizado'
        verbose_name_plural = 'Serviços realizados'
        constraints = [
            models.UniqueConstraint(fields=['agendamento', 'servico'], name='constraint_agendamento')
        ]

    def __str__(self):
        return self.servico.nome


    def calcular_valor_ordem(self):
        valor_total = 0
        qs = OrdemServicos.objects.filter(agendamento=self.agendamento)
        for item in qs:
            if item.situacao != 'C':
                valor_total += item.preco
        self.agendamento.valor = valor_total
        self.agendamento.save()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.preco = self.servico.preco
        super().save(force_insert, force_update, using, update_fields)
        self.calcular_valor_ordem()

    def delete(self, using=None, keep_parents=False):
        super().delete(using=None, keep_parents=keep_parents)
        self.calcular_valor_ordem()

agendamentos/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Agendamento, OrdemServicos
from clientes.models import Cliente
from funcionarios.models import Funcionario


class AgendamentoListForm(forms.Form):
    cliente = forms.ModelChoiceField(label='Cliente', queryset=Cliente.objects.all(), required=False)

    funcionario = forms.ModelChoiceField(label='Funcionario', queryset=Funcionario.objects.all(), required=False)

class AgendamentoModelForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        fields = ['horario', 'cliente', 'funcionario']

        error_messages = {
            'horario': {'required': 'O horário é um campo obrigatório'},
            'cliente': {'required': 'O cliente é um campo obrigatório'},
            'funcionario': {'required': 'O funcionario é um campo obrigatório'},
        }

AgendamentosServicoInLine = inlineformset_factory(
    Agendamento, OrdemServicos, fk_name='agendamento',
    fields=('servico', 'funcionario', 'situacao', 'observacoes'),
    extra=1, can_delete=True
)

agendamentos/views.py
from django.contrib.messages.context_processors import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib import messages
from django.views.generic.base import TemplateResponseMixin
from django.views import View

from produtos.models import Produto
from servicos.models import ProdutosServico
from .forms import AgendamentoListForm, AgendamentoModelForm, AgendamentosServicoInLine
from .models import Agendamento, OrdemServicos


class AgendamentosView(ListView):
    model = Agendamento
    template_name = 'agendamentos.html'

    def get_context_data(self, **kwargs):
        context = super(AgendamentosView, self).get_context_data(**kwargs)

        if self.request.GET:
            form = AgendamentoListForm(self.request.GET)
        else:
            form = AgendamentoListForm()
        context['form'] = form
        return context

    def get_queryset(self):
        qs = super(AgendamentosView, self).get_queryset()

        if self.request.GET:
            form = AgendamentoListForm(self.request.GET)

            if form.is_valid():
                cliente = form.cleaned_data.get('cliente')
                funcionario = form.cleaned_data.get('funcionario')

                if cliente:
                    qs = qs.filter(cliente=cliente)
                if funcionario:
                    qs = qs.filter(funcionario=funcionario)

        if qs.count() > 0:
            paginator = Paginator(qs, per_page=1)
            listagem = paginator.get_page(self.request.GET.get('page'))
            return listagem
        else:
            return messages.info(self.request, message='Não existem agendamentos cadastrados!')



class AgendamentoAddView(SuccessMessageMixin, CreateView):
    model = Agendamento
    form_class = AgendamentoModelForm
    template_name = 'agendamento_form.html'
    success_url = reverse_lazy('agendamentos')
    success_message = 'Agendamento cadastrado com sucesso!'

class AgendamentoUpdateView(SuccessMessageMixin, UpdateView):
    model = Agendamento
    form_class = AgendamentoModelForm
    template_name = 'agendamento_form.html'
    success_url = reverse_lazy('agendamentos')
    success_message = 'Agendamento alterado com sucesso!'

class AgendamentoDeleteView(SuccessMessageMixin, DeleteView):
    model = Agendamento
    template_name = 'agendamento_apagar.html'
    success_url = reverse_lazy('agendamentos')
    success_message = 'Agendamento apagado com sucesso!'

class AgendamentoToInLineEditView(TemplateResponseMixin, View):
    template_name = 'agendamento_form_inline.html'

    def get_formset(self, data=None):
        return AgendamentosServicoInLine(instance=self.agendamento, data=data)

    def dispatch(self, request, pk):
        self.agendamento = get_object_or_404(Agendamento, id=pk)
        return super().dispatch(request, pk)

    def get(self,request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response({'agendamento': self.agendamento, 'formset': formset})

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            dados = formset.cleaned_data
            for item in dados:
                if item.get('situacao') != 'C':
                    produtoservico = ProdutosServico.objects.filter(servico=item.get('servico'))
                    if produtoservico:
                        produto = Produto.objects.get(pk=prd.produto.pk)
                        if produto.quantidade < prd.quantidade and not item.get('DELETE'):
                            messages.error(self.request,
                                           f'Atenção! Quantidade em estoque insuficiente para o produto {produto.nome}')
                            return self.render_to_response({'agendamento': self.agendamento, 'formset': formset})
                        else:
                            formset.save()
                    else:
                        formset.save()
            return redirect('agendamentos')
        else:
            return self.render_to_response({'agendamento': self.agendamento,'formset': formset})

class AgendamentoExibir(DetailView):
    model = Agendamento
    template_name = 'agendamento_exibir.html'

    def get_object(self, queryset=None):
        agendamento = Agendamento.objects.get(pk=self.kwargs.get('pk'))
        if agendamento.status == 'A':
            ordem_servico = OrdemServicos.objects.filter(agendamento=agendamento)
            lista_situacao = ordem_servico.values_list('situacao', flat=True)
            if 'A' in lista_situacao:
                messages.info(self.request, "Ordem de serviço não pode ser encerrada. Existem serviços com a situação em aberto!")
            else:
                for ordem in ordem_servico:
                    if ordem.situacao == 'R':
                        if ordem.servico.produto:
                            produto_servico = ProdutosServico.objects.filter(servico=ordem.servico)
                            for item in produto_servico:
                                produto = Produto.objects.get(pk=item.produto.pk)
                                produto.quantidade -= item.quantidade
                                produto.save()
                        agendamento.status = 'F'
                        agendamento.save()
        return agendamento

agendamentos/templates/agendamento_apagar.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="card shadow m-3 col-md-6 mx-auto">
    <div class="card-body">
        <div class="row">
            <h3 class="text-center">Dados do Agendamento</h3>

            <p class="p-2 mt-2">
                <strong>Horário: </strong>{{ object.horario }}
            </p>
            <p class="p-2 mt-2">
                <strong>Cliente: </strong>{{ object.cliente }}
            </p>

            <p class="p-2 mt-2 text-danger">
                Confirma a exclusão do agendamento?
            </p>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-end">
                    {% bootstrap_button button_type="submit" content="Sim" %}
                    <a href="{% url 'agendamentos' %}" class="btn btn-secondary text-white" type="button">
                        <span class="text">Cancelar</span>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

agendamentos/templates/agendamento_exibir.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="card shadow m-3 col-md-6 mx-auto">
    <div class="card-body">
        <div class="row">
            <h3 class="text-center">Dados do Atendimento</h3>
            <p class="p-2 mt-2"><strong>Horário: </strong>{{ agendamento.horario }}</p>
            <p class="p-2 mt-2"><strong>Cliente: </strong>{{ agendamento.cliente }}</p>
            <p class="p-2 mt-2"><strong>Funcionário pessoalmente pelo atendimento: </strong>{{ agendamento.funcionario
                }}</p>

            <h4> Serviços realizados </h4>

            {% for servico in agendamento.servicos %}
                <p class="p-2 ml-6">{{ servico }} - R$ {{ servico.preco }} ({{ servico.get_situacao_display }}) -
                    Funcionário: {{ servico.funcionario }}</p>
                {% if servico.observacao %}
                    <p class="p-2 ml-6"><strong>Observação: </strong> {{ servico.observacao }} </p>
                {% endif %}
            {% endfor %}

            <p class="p-2 ml-4"><strong>Valor total: </strong>{{ agendamento.valor }}</p>
            <div class="text-end">
                <a href="#" class="btn btn-primary text-white" type="button">
                    <span class="text">Voltar</span>
                </a>
            </div>
        </div>
    </div>
</div>

agendamentos/templates/agendamento_form.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}'
    <div class="card shadow m-3 col-md-6 mx-auto">
        <div class="card-body">
            <div class="row">
                <h3 class="text-center">Cadastro de agendamento</h3>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="text-end">
                        {% bootstrap_button button_type="submit" content="Salvar" %}
                        <a href="{% url 'agendamentos' %}" class="btn btn-secondary text-white" type="button">
                           <span class="text">Cancelar</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

agendamentos/templates/agendamento_form_inline.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="card shadow m-3 col-md-6 mx-auto">
        <div class="card-body">
            <div class="row">
                <h3 class="text-center">Serviços realizados no agendamento</h3>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_formset formset layout='horizontal' %}
                    {{ formset.management_form }}
                    <div class="text-end">
                        {% bootstrap_button button_type="submit" content="Salvar" %}
                        <a href="{% url 'agendamentos' %}" class="btn btn-secondary text-white" type="button">
                           <span class="text">Cancelar</span>
                             </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

agendamentos/templates/agendamentos.html
{% extends 'principal.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<section class="section">
    <div class="container">
        <form action="" method="GET">
            <div class="form-group row p-3">
                <div class="col-sm-5">
                    {% bootstrap_field form.cliente layout='horizontal' %}
                </div>
                <div class="col-sm-5">
                    {% bootstrap_field form.funcionario layout='horizontal' %}
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-primary">
                        Buscar
                    </button>
                </div>
            </div>
        </form>

        {% if object_list %}
        <div class="card-body">
            <h3 class="text-center">Agendamentos Cadastrados</h3>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="table-success">
                        <tr>
                            <th>Horário</th>
                            <th>Cliente</th>
                            <th>Funcionário</th>
                            <th>Serviços</th>
                            <th style="width: 100px; text-align: center">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for agendamento in object_list %}
                        <tr>
                            <td>{{ agendamento.horario }}</td>
                            <td>{{ agendamento.cliente }}</td>
                            <td>{{ agendamento.funcionario }}</td>
                            <td>
                                {% for servico in agendamento.servicos %}
                                    {{ servico }} - R$ {{ servico.preco }} ({{servico.get_situacao_display }}) <br>
                                {% endfor %}
                                <strong>Valor total: {{ agendamento.valor }}</strong>
                            </td>
                            <td style="text-align: center">
                                {% if agendamento.status == 'A' %}
                                     <a href="{% url 'agendamento_inline' agendamento.pk %}">
                                        <span class="icon">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
                                    </a>
                                    <a href="{% url 'agendamento_editar' agendamento.pk %}">
                                        <span class="icon">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </a>

                                    <a href="{% url 'agendamento_apagar' agendamento.pk %}">
                                        <span class="icon">
                                            <i class="far fa-trash-alt"></i>
                                        </span>
                                    </a>
                                {% else %}
                                    <span class="icon">
                                        <i class="fas fa-pencil-alt"></i>
                                    </span>

                                    <span class="icon">
                                        <i class="fas fa-edit"></i>
                                    </span>
                                    <span class="icon">
                                        <i class="far fa-trash-alt"></i>
                                    </span>
                                {% endif %}
                                <a href="{% url 'agendamento_exibir' agendamento.pk %}">
                                    <span class="icon">
                                        <i class="fas fa-check-circle">
                                        </i>
                                    </span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    {% bootstrap_pagination object_list url='/agendamentos?page=1' size="sm" %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}